#!/usr/bin/env python3
"""
Generate the report's numbers straight out of the built warehouse.

Everything the design doc claims about the data — row counts, null rates,
cardinality, how many objects landed on each surface, how each external
company resolved — is read back from gtm_cdp.duckdb here rather than typed
into the HTML by hand. Run it after a build and the report is current; if a
number in the doc looks wrong, this is the only place it could have come from.

    dbt build
    pip install duckdb
    python docs/build_report_data.py

Rewrites the block between the REPORTDATA markers in docs/overview.html.

One rule for the prose that sits alongside this data (MODELNOTE in the page):
never restate a number this script already generates. A hand-written "25
candidate links" next to a generated "34" is exactly the drift the generators
exist to prevent. Describe the shape; let the generated column carry the count.
"""
from __future__ import annotations

import json
import pathlib
import sys
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parent.parent
DB = ROOT / "gtm_cdp.duckdb"
PAGE = ROOT / "docs" / "overview.html"
BEGIN = "/* ==REPORTDATA:BEGIN — generated by docs/build_report_data.py, do not edit== */"
END = "/* ==REPORTDATA:END== */"

# Delivered seeds, in the order the brief's own README lists them.
SEEDS = [
    ("raw_users", "product"), ("raw_members", "product"), ("raw_organizations", "product"),
    ("raw_projects", "product"), ("raw_experiments", "product"), ("raw_datasets", "product"),
    ("raw_prompts", "product"), ("raw_segment_pages", "product"), ("raw_cli_wizard", "product"),
    ("raw_docs_mcp_events", "product"), ("raw_api_keys", "product"), ("raw_trace_volume", "product"),
    ("raw_salesforce_accounts", "crm"), ("raw_account_org_map", "crm"),
    ("raw_signal_companies", "signals"), ("raw_news_events", "signals"),
    ("raw_products", "signals"), ("raw_tech_detections", "signals"),
]

MODELS = [
    ("cleansed", "int_user_identity"), ("cleansed", "int_org_account_resolution"),
    ("cleansed", "int_org_trace_trend"), ("cleansed", "int_match_keys"),
    ("cleansed", "int_memberships"), ("cleansed", "int_api_keys"),
    ("cleansed", "int_account_trace_trend"), ("cleansed", "int_signal_company_match_candidates"),
    ("cleansed", "int_member_account_resolution"), ("cleansed", "int_signal_company_resolution"),
    ("cleansed", "int_product_activity"), ("cleansed", "int_external_signals"),
    ("unified", "fct_member_surface_activity"), ("unified", "fct_account_surface_adoption"),
    ("unified", "fct_account_signals"), ("unified", "dim_members"),
    ("unified", "dim_signal_companies"), ("unified", "account_360"),
    ("unified", "net_new_prospects"), ("unified", "rpt_resolution_quality"),
]


def main() -> int:
    try:
        import duckdb
    except ImportError:
        print("error: pip install duckdb", file=sys.stderr)
        return 1
    if not DB.exists():
        print(f"error: {DB.name} not found — run `dbt build` first.", file=sys.stderr)
        return 1

    con = duckdb.connect(str(DB), read_only=True)

    def rows(sql: str) -> list[tuple]:
        return con.execute(sql).fetchall()

    def one(sql: str):
        r = con.execute(sql).fetchone()
        return r[0] if r else None

    # ── 1. seed profile: shape, null rate and cardinality per column ─────────
    profile = []
    for name, group in SEEDS:
        cols = rows(f"select column_name, data_type from information_schema.columns "
                    f"where table_schema='raw' and table_name='{name}' order by ordinal_position")
        n = one(f'select count(*) from raw."{name}"')
        colinfo = []
        for cname, ctype in cols:
            q = f'''select
                      sum(case when "{cname}" is null or trim(cast("{cname}" as varchar))='' then 1 else 0 end),
                      count(distinct "{cname}")
                    from raw."{name}"'''
            nulls, distinct = rows(q)[0]
            colinfo.append({
                "n": cname,
                "t": ctype.lower().replace("character varying", "varchar").replace("timestamp without time zone", "timestamp"),
                "null": int(nulls or 0),
                "d": int(distinct or 0),
                "uniq": bool(distinct == n and n > 1),
            })
        profile.append({"n": name, "g": group, "rows": n, "cols": len(cols), "c": colinfo})

    # ── 2. model row counts ──────────────────────────────────────────────────
    model_rows = [{"n": m, "l": lay, "rows": one(f'select count(*) from {lay}."{m}"')} for lay, m in MODELS]

    # ── 3. the analyses the report actually argues from ──────────────────────
    analysis = {
        "surface": [
            {"code": r[0], "surface": r[1], "kind": r[2], "attr": r[3], "conf": float(r[4]),
             "actor": r[5], "n": r[6]}
            for r in rows("""select signal_code, surface, evidence_kind, attribution, confidence_score,
                                    actor_type, count(*)
                             from cleansed.int_product_activity
                             group by 1,2,3,4,5,6 order by surface, signal_code, actor_type""")
        ],
        "objects": [
            {"surface": r[0], "attr": r[1], "n": r[2]}
            for r in rows("""select surface, attribution, count(*) from cleansed.int_product_activity
                             where activity_type in ('experiment','dataset','prompt')
                             group by 1,2 order by 1,2""")
        ],
        "org": [
            {"org": r[0], "plan": r[1], "acct": r[2], "src": r[3], "conf": r[4], "status": r[5]}
            for r in rows("""select org_id, plan, coalesce(account_id,'—'), coalesce(mapping_source,'—'),
                                    coalesce(cast(mapping_confidence as varchar),'—'), resolution_status
                             from cleansed.int_org_account_resolution order by org_id""")
        ],
        "people": [
            {"p": r[0], "email": r[1], "orgs": r[2], "acct": r[3], "conf": r[4], "status": r[5], "logins": r[6]}
            for r in rows("""select person_id, email, coalesce(org_ids,'—'), coalesce(account_id,'—'),
                                    coalesce(cast(account_confidence as varchar),'—'), resolution_status, login_count
                             from cleansed.int_member_account_resolution order by person_id""")
        ],
        "companies": [
            {"id": r[0], "name": r[1], "status": r[2], "acct": r[3], "method": r[4],
             "conf": r[5], "review": r[6], "action": r[7], "km": r[8], "ka": r[9], "uk": r[10],
             "ev": r[11] or "—", "nameacct": r[12], "namekey": r[13]}
            for r in rows("""select company_id, company_name, resolution_status, coalesce(account_id,'—'),
                                    coalesce(match_method,'—'), coalesce(cast(match_confidence as varchar),'—'),
                                    needs_review, next_action, keys_matched, keys_agreeing,
                                    unique_keys_agreeing, match_evidence,
                                    name_match_account_id, name_key
                             from cleansed.int_signal_company_resolution r
                             join (select entity_id, name_key from cleansed.int_match_keys
                                   where entity_type = 'company') k on k.entity_id = r.company_id
                             order by company_id""")
        ],
        "members": [
            {"p": r[0], "email": r[1], "acct": r[2], "type": r[3], "ui": r[4], "sdk": r[5],
             "sdkany": r[6], "cli": r[7], "mcp": r[8], "human": r[9], "auto": r[10], "keys": r[11] or "—"}
            for r in rows("""select person_id, email, coalesce(account_id,'—'), member_type,
                                    ui_evidence, sdk_evidence, coalesce(sdk_evidence_any_actor,'—'),
                                    cli_evidence, mcp_evidence, human_usage_events, automated_usage_events,
                                    api_key_names
                             from unified.dim_members order by person_id""")
        ],
        "adoption": [
            {"acct": r[0], "surface": r[1], "meas": r[2], "known": r[3], "proven": r[4],
             "intent": r[5], "auto": r[6], "status": r[7], "level": r[8],
             "pct": (None if r[9] is None else float(r[9])), "summary": r[10]}
            for r in rows("""select account_id, surface, usage_is_measurable, known_members,
                                    members_usage_proven, members_intent_only, members_automation_only,
                                    account_evidence_status, evidence_level, pct_members_usage_proven,
                                    honest_summary
                             from unified.fct_account_surface_adoption order by account_id, surface_order""")
        ],
        "a360": [
            {"rank": r[0], "id": r[1], "name": r[2], "plan": r[3] or "—", "members": r[4],
             "active": r[5], "ui": r[6] or "—", "sdk": r[7] or "—", "sdklvl": r[8] or "—",
             "cli": r[9] or "—", "mcp": r[10] or "—", "gb": r[11], "growth": r[12],
             "sig": r[13], "review": r[14], "pend": r[15], "conf": r[16],
             "reasons": r[17] or "", "gaps": r[18] or "—"}
            for r in rows("""select priority_rank, account_id, account_name, best_plan, known_members,
                                    active_members_in_lookback, ui_adoption, sdk_adoption, sdk_evidence_level,
                                    cli_adoption, mcp_adoption, trace_gb_last_7d, trace_growth_7d,
                                    actionable_signals, signals_needing_review,
                                    external_records_pending_review, external_records_awaiting_confirmation,
                                    action_reasons, crm_identifier_gaps
                             from unified.account_360 order by priority_rank""")
        ],
        "signals": [
            {"id": r[0], "acct": r[1], "src": r[2], "type": r[3], "when": str(r[4])[:10],
             "head": r[5], "conf": float(r[6]), "attr": r[7],
             "aconf": (None if r[8] is None else float(r[8])), "act": r[9], "rev": r[10]}
            for r in rows("""select signal_id, account_id, signal_source, signal_type, occurred_at, headline,
                                    signal_confidence, attribution, attribution_confidence, is_actionable, needs_review
                             from unified.fct_account_signals order by account_id, signal_id""")
        ],
        "quality": [
            {"o": r[0], "area": r[1], "metric": r[2], "num": r[3], "den": r[4],
             "rate": (None if r[5] is None else float(r[5]))}
            for r in rows("""select metric_order, area, metric, numerator, denominator, rate
                             from unified.rpt_resolution_quality order by metric_order""")
        ],
        "prospects": [
            {"id": r[0], "src": r[1], "name": r[2], "dom": r[3] or "—", "plan": r[4] or "—",
             "members": r[5], "sig": r[6], "why": r[7], "head": r[8] or "—"}
            for r in rows("""select prospect_id, prospect_source, prospect_name, domain, product_plan,
                                    product_members, signals_in_lookback, why_it_matters, latest_headline
                             from unified.net_new_prospects order by prospect_source, prospect_id""")
        ],
        "traces": [
            {"org": r[0], "days": r[1], "gb7": float(r[2]), "first": float(r[3]),
             "last": float(r[4]), "growth": float(r[5])}
            for r in rows("""select org_id, days_with_data, gb_last_7d, gb_baseline_day, gb_last_day, growth_7d
                             from cleansed.int_org_trace_trend order by org_id""")
        ],
        "keys": [
            {"type": r[0], "id": r[1], "name": r[2], "dom": r[3] or "—", "slug": r[4] or "—",
             "key": r[5] or "—", "tok": r[6] or "—", "shared": r[7]}
            for r in rows("""select entity_type, entity_id, entity_name, domain_key, linkedin_slug,
                                    name_key, name_first_token, is_domain_shared
                             from cleansed.int_match_keys order by entity_type, entity_id""")
        ],
    }

    totals = {
        "seedRows": sum(p["rows"] for p in profile),
        "seedCols": sum(p["cols"] for p in profile),
        "objects": one("""select count(*) from cleansed.int_product_activity
                          where activity_type in ('experiment','dataset','prompt')"""),
        "activities": one("select count(*) from cleansed.int_product_activity"),
        "attributed": one("select count(*) from cleansed.int_product_activity where account_id is not null"),
        "nullCells": sum(c["null"] for p in profile for c in p["c"]),
        "cells": sum(p["rows"] * p["cols"] for p in profile),
    }

    payload = {
        "gen": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        "totals": totals, "profile": profile, "models": model_rows, "a": analysis,
    }

    block = "\n".join([
        BEGIN,
        "var DATA = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";",
        END,
    ])

    page = PAGE.read_text()
    i, j = page.find(BEGIN), page.find(END)
    if i == -1 or j == -1:
        print("error: REPORTDATA markers not found in docs/overview.html", file=sys.stderr)
        return 1
    PAGE.write_text(page[:i] + block + page[j + len(END):])

    print(f"docs/overview.html · {len(profile)} seeds profiled ({totals['seedRows']} rows, "
          f"{totals['seedCols']} columns), {len(model_rows)} models counted, "
          f"{sum(len(v) for v in analysis.values())} analysis rows, {len(block)//1024} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
