#!/usr/bin/env python3
"""
Generate the lineage graph in docs/overview.html from dbt's own manifest.

The diagram in the design doc is not drawn by hand. Its nodes, its layers, its
four CLEANSED passes and every edge come out of target/manifest.json, so the
picture cannot drift from the DAG dbt actually builds. Only the one-line
descriptions are editorial, and NOTES below is checked against the manifest on
every run: an undocumented model, or a note for a model that no longer exists,
is an error rather than a silently stale diagram.

    dbt build                      # or: dbt parse / dbt compile
    python docs/build_lineage.py

Rewrites the block between the LINEAGE markers in docs/overview.html.
"""
from __future__ import annotations

import json
import pathlib
import sys
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "target" / "manifest.json"
PAGE = ROOT / "docs" / "overview.html"
BEGIN = "/* ==LINEAGE:BEGIN — generated by docs/build_lineage.py, do not edit== */"
END = "/* ==LINEAGE:END== */"

# ── editorial layer: one line per object. Structure comes from the manifest. ──
NOTES: dict[str, tuple[str, str]] = {
    # grain, description
    "raw_users": ("one per login", "user_id + email. Nine rows, eight people."),
    "raw_members": ("user × org", "Genuinely many-to-many, and one person spans two accounts."),
    "raw_organizations": ("one per org", "Carries the plan (Enterprise / Pro / Free), in mixed case."),
    "raw_projects": ("one per project", "Every project belongs to exactly one org — the safe attribution path."),
    "raw_experiments": ("one per experiment", "repo_info + metadata as JSON text. The richest origin evidence in the dataset."),
    "raw_datasets": ("one per dataset", "metadata JSON only, and its source field is free text."),
    "raw_prompts": ("one per prompt", "No metadata column at all, so origin is unknowable by construction."),
    "raw_segment_pages": ("page view", "user_id is null for anonymous traffic. The only deterministic UI signal."),
    "raw_cli_wizard": ("wizard view", "Fires in the BROWSER, not the CLI. Intent, never usage."),
    "raw_docs_mcp_events": ("docs click", "“Install / copy MCP command” clicks. Intent, never usage."),
    "raw_api_keys": ("one per key", "Hash only, plus a free-text name. Objects do not record which key made them."),
    "raw_trace_volume": ("org × day GB", "No user_id at this grain, so it can never be split across members."),
    "raw_salesforce_accounts": ("one per account", "Ten accounts. Domain and LinkedIn sometimes null; two share a domain."),
    "raw_account_org_map": ("org → account", "Carries mapping_source, which is where the confidence comes from."),
    "raw_signal_companies": ("one per company", "No Salesforce id — only a messy website, a LinkedIn URL and a LinkedIn domain."),
    "raw_news_events": ("one per news event", "Vendor confidence 0.4–0.98. One headline names a different company than its key."),
    "raw_products": ("one per product", "Overlaps the news feed: two launches appear in both."),
    "raw_tech_detections": ("one per detection", "Stack context, never a reason to call."),
    "ref_surface_signals": ("one per signal", "The surface catalogue: what each signal proves, what it cannot, and how confidently. Nine rows."),
    "ref_org_mapping_sources": ("one per link type", "contract 0.95 › billing_parent 0.85 › org_c_fallback 0.50."),
    "ref_external_match_rules": ("one per match key", "linkedin_slug 0.90 › website_domain 0.85 › linkedin_domain 0.75; company_name can_resolve = false."),

    "stg_product__experiments": ("1:1 with its seed", "Parses repo_info and metadata JSON into ordinary columns — repo_is_dirty, repo_author_name, meta_ci_run_id — so no later layer touches JSON."),
    "stg_product__datasets": ("1:1 with its seed", "Parses metadata JSON into meta_source."),
    "stg_product__cli_wizard": ("1:1 with its seed", "Named to make the trap obvious: these are browser events, not CLI invocations."),
    "stg_product__trace_volume": ("1:1 with its seed", "Typed org × day. The model comment states plainly that there is no user_id here."),
    "stg_signals__companies": ("1:1 with its seed", "Types the three messy identifiers without touching them — normalisation belongs downstream, in one place."),

    "int_user_identity": ("one per login", "Which logins are the same person. Exact, case-insensitive email only — both ids kept, one flagged secondary. Nothing fuzzier is merged."),
    "int_org_account_resolution": ("one per org", "Which account an org rolls up to, and how much to trust it. The rule seed turns the link type into a confidence; two candidate accounts means none."),
    "int_org_trace_trend": ("one per org", "Seven-day volume ending on the as-of date, and growth against the day before that window. Org level, because there is no user column to split it by."),
    "int_match_keys": ("one per matchable entity", "THE normaliser. Every Salesforce account and every external company go through the same CTEs, so a key built from the CRM and a key built from the vendor feed can never drift apart. Decides nothing."),
    "int_memberships": ("person × org", "Collapses a person’s duplicate logins into one membership row and carries the org’s account resolution with it."),
    "int_api_keys": ("one per API key", "Whose key it is, plus the free-text name hints (ci-service, dave-cli) that stay hints and never become evidence of usage."),
    "int_account_trace_trend": ("one per account", "Rolls org traces up to the account and owns the definition of “trace growth”. Three marts read it instead of each recomputing the ratio."),
    "int_signal_company_match_candidates": ("company × method × account", "Every possible link, one row per key that matched. Deliberately refuses to choose — that is the next model’s job."),
    "int_member_account_resolution": ("one per person", "One account per person, and only if all their orgs agree. Frank spans Globex and Umbrella, so he gets none and is marked ambiguous."),
    "int_signal_company_resolution": ("one per external company", "The CDP core. Precedence picks a winner, every other key must agree, a name can only object. Outcome is resolved / conflict / ambiguous / unmatched / no_identifiers — never a guess."),
    "int_product_activity": ("one per activity", "Every object, page view, wizard view, docs click and CLI-named key becomes one row carrying surface, usage-or-intent, attribution class, confidence and human-or-automation."),
    "int_external_signals": ("one per signal", "News, products and tech as one stream. Cross-feed duplicates merged and marked corroborated; a headline naming a different company is flagged and never actionable."),

    "fct_member_surface_activity": ("person × surface", "Every person gets a row for every surface, so “no evidence” is an explicit answer. Two status columns: evidence_status (anyone) and human_evidence_status (the person, automation excluded)."),
    "fct_account_surface_adoption": ("account × surface", "The rollup, with known_members as the denominator — product members, not headcount. evidence_level says whether the proof is member-level or only org-level."),
    "fct_account_signals": ("one per signal", "The extension point: product and external signals in one shape. A new source is one more union branch."),
    "dim_members": ("one per person", "Who they are, which account, member type, evidence per surface. The *_evidence columns count people only."),
    "dim_signal_companies": ("one per external company", "Every company, resolved or not, with its evidence and its next_action."),
    "account_360": ("one per Salesforce account", "The rep view: who they are, how they use the product, what has happened lately, and ranked plain-English reasons to call."),
    "net_new_prospects": ("one per prospect", "Unmatched external companies plus product sign-ups with no CRM account. An output, not an error."),
    "rpt_resolution_quality": ("one per metric", "Nineteen resolution metrics recomputed every run, so drift is visible the moment an upstream feed changes."),
}
GENERIC_STG = ("1:1 with its seed",
               "Typed 1:1 view: rename, cast, empty string → null. No business logic, so swapping the seed "
               "for a landed table is a one-line change.")

PASS_LABEL = {0: "1 · Make comparable", 1: "2 · Relate", 2: "3 · Decide", 3: "4 · Classify"}
SRC_GROUP = {"product": "Product · delivered", "crm": "CRM · delivered", "signals": "External · delivered"}
RAW_GROUP = {"product": "Product", "crm": "CRM", "signals": "External"}


def js(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def main() -> int:
    if not MANIFEST.exists():
        print(f"error: {MANIFEST.relative_to(ROOT)} not found — run `dbt build` (or `dbt parse`) first.", file=sys.stderr)
        return 1

    man = json.loads(MANIFEST.read_text())
    raw = {**man["nodes"], **man.get("sources", {})}
    keep = {
        uid: nd for uid, nd in raw.items()
        if nd["resource_type"] in ("model", "seed") and nd["package_name"] == "gtm_cdp"
    }
    name_of = {uid: nd["name"] for uid, nd in keep.items()}

    # ── layer + sub-directory, straight off the file path ────────────────────
    layer, subdir = {}, {}
    for uid, nd in keep.items():
        parts = pathlib.PurePosixPath(nd["path"]).parts
        if nd["resource_type"] == "seed":
            layer[uid] = "source"
            subdir[uid] = parts[0] if len(parts) > 1 else "raw"
        else:
            layer[uid] = parts[0]                       # raw | cleansed | unified
            subdir[uid] = parts[1] if len(parts) > 2 else ""

    edges = []
    parents: dict[str, list[str]] = {}
    for uid, nd in keep.items():
        for p in nd.get("depends_on", {}).get("nodes", []):
            if p in keep:
                edges.append((name_of[p], name_of[uid]))
                parents.setdefault(uid, []).append(p)

    # ── a delivered seed inherits its group from the staging model that reads
    #    it, so even the Product / CRM / External split is manifest-derived ───
    seed_group = {}
    for uid, nd in keep.items():
        if layer[uid] != "raw":
            continue
        for p in parents.get(uid, []):
            if layer[p] == "source":
                seed_group[p] = subdir[uid]

    # ── the four CLEANSED passes = depth within the cleansed sub-graph ───────
    depth: dict[str, int] = {}

    def cleansed_depth(uid: str) -> int:
        if uid in depth:
            return depth[uid]
        depth[uid] = 0                                   # cycle guard; dbt has none
        d = 0
        for p in parents.get(uid, []):
            if layer[p] == "cleansed":
                d = max(d, cleansed_depth(p) + 1)
        depth[uid] = d
        return d

    nodes = []
    for uid, nd in keep.items():
        nm, lay = name_of[uid], layer[uid]
        if lay == "source":
            new = subdir[uid] != "raw"
            grp = "Rules · introduced" if new else SRC_GROUP.get(seed_group.get(uid, ""), "Delivered")
            rank = {"Product · delivered": 0, "CRM · delivered": 1, "External · delivered": 2}.get(grp, 3)
            order = (rank, "", nm)
        elif lay == "raw":
            new, grp = True, RAW_GROUP.get(subdir[uid], "Other")
            order = (0, {"Product": "a", "CRM": "b", "External": "c"}[grp], nm)
        elif lay == "cleansed":
            new, grp = True, PASS_LABEL.get(cleansed_depth(uid), "Later")
            order = (cleansed_depth(uid), "", nm)
        else:
            new = True
            grp = "Facts" if nm.startswith("fct_") else "Dimensions" if nm.startswith("dim_") else "Reports"
            order = ({"Facts": 0, "Dimensions": 1, "Reports": 2}[grp], "", nm)

        grain, desc = NOTES.get(nm, GENERIC_STG if nm.startswith("stg_") else ("", ""))
        if not desc:
            print(f"error: no NOTES entry for {nm} — add one, or the diagram will ship undocumented.", file=sys.stderr)
            return 1
        nodes.append((order, nm, lay, grp, 1 if new else 0, grain, desc))

    stale = set(NOTES) - set(name_of.values())
    if stale:
        print(f"error: NOTES has entries for objects not in the manifest: {sorted(stale)}", file=sys.stderr)
        return 1

    nodes.sort(key=lambda r: (["source", "raw", "cleansed", "unified"].index(r[2]), r[0]))
    edges.sort()

    meta = man.get("metadata", {})
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    counts = {lay: sum(1 for n in nodes if n[2] == lay) for lay in ("source", "raw", "cleansed", "unified")}
    delivered = sum(1 for n in nodes if not n[4])

    out = [BEGIN]
    out.append("/* dbt v%s · manifest schema %s · %d nodes, %d edges */" % (
        meta.get("dbt_version", "?"), meta.get("dbt_schema_version", "?").rsplit("/", 1)[-1], len(nodes), len(edges)))
    out.append("var BUILD = {gen:%s, dbt:%s, nodes:%d, edges:%d, delivered:%d, introduced:%d, "
               "source:%d, raw:%d, cleansed:%d, unified:%d};" % (
                   js(stamp), js(meta.get("dbt_version", "?")), len(nodes), len(edges),
                   delivered, len(nodes) - delivered,
                   counts["source"], counts["raw"], counts["cleansed"], counts["unified"]))
    out.append("var N = [")
    for _, nm, lay, grp, new, grain, desc in nodes:
        out.append("  {id:%s, col:%s, grp:%s, neu:%d, grain:%s, desc:%s}," % (
            js(nm), js(lay), js(grp), new, js(grain), js(desc)))
    out.append("];")
    out.append("var E = [")
    for a, b in edges:
        out.append("  [%s,%s]," % (js(a), js(b)))
    out.append("];")
    out.append(END)
    block = "\n".join(out)

    page = PAGE.read_text()
    i, j = page.find(BEGIN), page.find(END)
    if i == -1 or j == -1:
        print("error: LINEAGE markers not found in docs/overview.html", file=sys.stderr)
        return 1
    PAGE.write_text(page[:i] + block + page[j + len(END):])

    print(f"docs/overview.html · {len(nodes)} nodes ({delivered} delivered, {len(nodes)-delivered} introduced), "
          f"{len(edges)} edges, from dbt {meta.get('dbt_version','?')} manifest")
    for lay in ("source", "raw", "cleansed", "unified"):
        print(f"  {lay:<9} {counts[lay]:>2}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
